// libraries
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <unistd.h>

// constants definition
#define MIN 0
#define MAX 255
#define SIZE 20
#define DELAY 10000 // 10000 microseconds = 10 milliseconds
#define CONSTANT 123

// this function generates 'size' 8bit random numbers between 'min' and
// 'max' range and stores them in an array
void writeRandomNumbers(int *randomArray, int min, int max, int size) {

    int i;
    
    for(i = 0; i < size; i++) {  	

        randomArray[i] = (rand() % (max - min + 1)) + min;
                
        printf("%d \n", randomArray[i]);        
        
    }
    
    printf("\n");
    
}

// this function read 'size' 8 bit random numbers generated by the first
// thread
void readRandomNumbers(int *randomArray, int size, int constant) {
	
    int i;
    
    for(i = 0; i < size; i++) {  	
        
        int number = randomArray[i] & constant;
        
        char charNumber = number + '0';
                
        printf("%c \n", charNumber);
        
    }
    
}

// this functions belogns to thread 1
void *thread1Function(void *voidRandomArray) {

    int* randomArray;
    randomArray = (int*)voidRandomArray;
	
    while(1) {
    			
		writeRandomNumbers(randomArray, MIN, MAX, SIZE);
    		                      
		printf("********** \n\n");
		
		usleep(10000);
        
    }
    
}

// this functions belogns to thread 2
void *thread2Function(void *voidRandomArray) {

    int* randomArray;
    randomArray = (int*)voidRandomArray;
	
    while(1) {
    				
		readRandomNumbers(randomArray, SIZE, CONSTANT);
		                      
		printf("********** \n\n");
		
		usleep(10000);
        
    }
    
}

int main() {
		
	int *randomArray;    
    randomArray = (int*)calloc(SIZE, sizeof(int));
	
	pthread_t thread1;
	pthread_t thread2;
	
	int write = pthread_create(&thread1, NULL, thread1Function, (void*) randomArray);
	int read = pthread_create(&thread2, NULL, thread2Function, (void*) randomArray);

	pthread_join(thread1, NULL);
	pthread_join(thread2, NULL); 
		
	return 0;
     
}
